import React from "react";
import classNames from "classnames";

export default class Flag extends React.Component {

  	render() {

        const logos = ["flag-icon-ad","flag-icon-ae","flag-icon-af","flag-icon-ag","flag-icon-ai","flag-icon-al","flag-icon-am","flag-icon-ao","flag-icon-aq","flag-icon-ar","flag-icon-as","flag-icon-at","flag-icon-au","flag-icon-aw","flag-icon-ax","flag-icon-az","flag-icon-ba","flag-icon-bb","flag-icon-bd","flag-icon-be","flag-icon-bf","flag-icon-bg","flag-icon-bh","flag-icon-bi","flag-icon-bj","flag-icon-bl","flag-icon-bm","flag-icon-bn","flag-icon-bo","flag-icon-bq","flag-icon-br","flag-icon-bs","flag-icon-bt","flag-icon-bv","flag-icon-bw","flag-icon-by","flag-icon-bz","flag-icon-ca","flag-icon-cc","flag-icon-cd","flag-icon-cf","flag-icon-cg","flag-icon-ch","flag-icon-ci","flag-icon-ck","flag-icon-cl","flag-icon-cm","flag-icon-cn","flag-icon-co","flag-icon-cr","flag-icon-cu","flag-icon-cv","flag-icon-cw","flag-icon-cx","flag-icon-cy","flag-icon-cz","flag-icon-de","flag-icon-dj","flag-icon-dk","flag-icon-dm","flag-icon-do","flag-icon-dz","flag-icon-ec","flag-icon-ee","flag-icon-eg","flag-icon-eh","flag-icon-er","flag-icon-es","flag-icon-et","flag-icon-fi","flag-icon-fj","flag-icon-fk","flag-icon-fm","flag-icon-fo","flag-icon-fr","flag-icon-ga","flag-icon-gb","flag-icon-gd","flag-icon-ge","flag-icon-gf","flag-icon-gg","flag-icon-gh","flag-icon-gi","flag-icon-gl","flag-icon-gm","flag-icon-gn","flag-icon-gp","flag-icon-gq","flag-icon-gr","flag-icon-gs","flag-icon-gt","flag-icon-gu","flag-icon-gw","flag-icon-gy","flag-icon-hk","flag-icon-hm","flag-icon-hn","flag-icon-hr","flag-icon-ht","flag-icon-hu","flag-icon-id","flag-icon-ie","flag-icon-il","flag-icon-im","flag-icon-in","flag-icon-io","flag-icon-iq","flag-icon-ir","flag-icon-is","flag-icon-it","flag-icon-je","flag-icon-jm","flag-icon-jo","flag-icon-jp","flag-icon-ke","flag-icon-kg","flag-icon-kh","flag-icon-ki","flag-icon-km","flag-icon-kn","flag-icon-kp","flag-icon-kr","flag-icon-kw","flag-icon-ky","flag-icon-kz","flag-icon-la","flag-icon-lb","flag-icon-lc","flag-icon-li","flag-icon-lk","flag-icon-lr","flag-icon-ls","flag-icon-lt","flag-icon-lu","flag-icon-lv","flag-icon-ly","flag-icon-ma","flag-icon-mc","flag-icon-md","flag-icon-me","flag-icon-mf","flag-icon-mg","flag-icon-mh","flag-icon-mk","flag-icon-ml","flag-icon-mm","flag-icon-mn","flag-icon-mo","flag-icon-mp","flag-icon-mq","flag-icon-mr","flag-icon-ms","flag-icon-mt","flag-icon-mu","flag-icon-mv","flag-icon-mw","flag-icon-mx","flag-icon-my","flag-icon-mz","flag-icon-na","flag-icon-nc","flag-icon-ne","flag-icon-nf","flag-icon-ng","flag-icon-ni","flag-icon-nl","flag-icon-no","flag-icon-np","flag-icon-nr","flag-icon-nu","flag-icon-nz","flag-icon-om","flag-icon-pa","flag-icon-pe","flag-icon-pf","flag-icon-pg","flag-icon-ph","flag-icon-pk","flag-icon-pl","flag-icon-pm","flag-icon-pn","flag-icon-pr","flag-icon-ps","flag-icon-pt","flag-icon-pw","flag-icon-py","flag-icon-qa","flag-icon-re","flag-icon-ro","flag-icon-rs","flag-icon-ru","flag-icon-rw","flag-icon-sa","flag-icon-sb","flag-icon-sc","flag-icon-sd","flag-icon-se","flag-icon-sg","flag-icon-sh","flag-icon-si","flag-icon-sj","flag-icon-sk","flag-icon-sl","flag-icon-sm","flag-icon-sn","flag-icon-so","flag-icon-sr","flag-icon-ss","flag-icon-st","flag-icon-sv","flag-icon-sx","flag-icon-sy","flag-icon-sz","flag-icon-tc","flag-icon-td","flag-icon-tf","flag-icon-tg","flag-icon-th","flag-icon-tj","flag-icon-tk","flag-icon-tl","flag-icon-tm","flag-icon-tn","flag-icon-to","flag-icon-tr","flag-icon-tt","flag-icon-tv","flag-icon-tw","flag-icon-tz","flag-icon-ua","flag-icon-ug","flag-icon-um","flag-icon-us","flag-icon-uy","flag-icon-uz","flag-icon-va","flag-icon-vc","flag-icon-ve","flag-icon-vg","flag-icon-vi","flag-icon-vn","flag-icon-vu","flag-icon-wf","flag-icon-ws","flag-icon-ye","flag-icon-yt","flag-icon-za","flag-icon-zm","flag-icon-zw","flag-icon-eu","flag-icon-gb-eng","flag-icon-gb-nir","flag-icon-gb-sct","flag-icon-gb-wls","flag-icon-un"]
        const flags =  { "138" :"flag-icon-pt",
            "145" :"flag-icon-se",
            "147" :"flag-icon-ru",
            "15416" :"flag-icon-id",
            "15648" :"flag-icon-no",
            "15820" :"flag-icon-ar",
            "15823" :"flag-icon-bo",
            "16133" :"flag-icon-at",
            "16135" :"flag-icon-be",
            "16143" :"flag-icon-cl",
            "16181" :"flag-icon-pt",
            "16183" :"flag-icon-ru",
            "16508" :"flag-icon-cn",
            "16509" :"flag-icon-hr",
            "1690" :"flag-icon-ch",
            "1711" :"flag-icon-de",
            "17145" :"flag-icon-gb-eng",
            "17146" :"flag-icon-gb-eng",
            "17211" :"flag-icon-de",
            "17212" :"flag-icon-de",
            "17213" :"flag-icon-de",
            "17214" :"flag-icon-de",
            "1749" :"flag-icon-pl",
            "187" :"flag-icon-br",
            "1874" :"flag-icon-au",
            "1875" :"flag-icon-at",
            "1877" :"flag-icon-ie",
            "1882" :"flag-icon-gb-sct",
            "1883" :"flag-icon-gb-sct",
            "18853" :"flag-icon-ar",
            "19" :"flag-icon-fr",
            "19149" :"flag-icon-co",
            "19472" :"flag-icon-sk",
            "19605" :"flag-icon-ro",
            "19636" :"flag-icon-at",
            "19707" :"flag-icon-it",
            "19709" :"flag-icon-it",
            "19764" :"flag-icon-dz",
            "201" :"flag-icon-br",
            "20166" :"flag-icon-gb-eng",
            "20167" :"flag-icon-gb-eng",
            "20673" :"flag-icon-ps",
            "20697" :"flag-icon-at",
            "21" :"flag-icon-nl",
            "21127" :"flag-icon-gb-eng",
            "21136" :"flag-icon-be",
            "21137" :"flag-icon-nl",
            "21163" :"flag-icon-in",
            "220" :"flag-icon-cz",
            "221" :"flag-icon-pl",
            "229" :"flag-icon-gb-eng",
            "230" :"flag-icon-ar",
            "2597" :"flag-icon-ec",
            "2598" :"flag-icon-uy",
            "26" :"flag-icon-be",
            "2645" :"flag-icon-gb-wls",
            "2646" :"flag-icon-co",
            "27" :"flag-icon-ch",
            "28" :"flag-icon-gb-eng",
            "2836" :"flag-icon-pl",
            "29" :"flag-icon-de",
            "3" :"flag-icon-gb-eng",
            "30" :"flag-icon-it",
            "31" :"flag-icon-es",
            "3102" :"flag-icon-eg",
            "3142" :"flag-icon-ma",
            "3143" :"flag-icon-dz",
            "32" :"flag-icon-pt",
            "3297" :"flag-icon-by",
            "33" :"flag-icon-gb-sct",
            "3301" :"flag-icon-jp",
            "3302" :"flag-icon-pe",
            "3303" :"flag-icon-ru",
            "3331" :"flag-icon-it",
            "3454" :"flag-icon-br",
            "35" :"flag-icon-at",
            "3584" :"flag-icon-cl",
            "36" :"flag-icon-fr",
            "37" :"flag-icon-tr",
            "38" :"flag-icon-gr",
            "4" :"flag-icon-fr",
            "40" :"flag-icon-fr",
            "4219" :"flag-icon-cz",
            "432" :"flag-icon-mx",
            "44" :"flag-icon-gb-eng",
            "4625" :"flag-icon-tr",
            "4626" :"flag-icon-qa",
            "4627" :"flag-icon-za",
            "4666" :"flag-icon-ae",
            "5" :"flag-icon-de",
            "50" :"flag-icon-it",
            "500" :"flag-icon-be",
            "503" :"flag-icon-jp",
            "5036" :"flag-icon-sa",
            "5037" :"flag-icon-gb-eng",
            "504" :"flag-icon-us",
            "53" :"flag-icon-fr",
            "530" :"flag-icon-ua",
            "531" :"flag-icon-hr",
            "532" :"flag-icon-de",
            "536" :"flag-icon-dk",
            "537" :"flag-icon-gb-eng",
            "539" :"flag-icon-nl",
            "5472" :"flag-icon-il",
            "548" :"flag-icon-bg",
            "549" :"flag-icon-sl",
            "5490" :"flag-icon-jo",
            "5499" :"flag-icon-ar",
            "55" :"flag-icon-de",
            "551" :"flag-icon-gb-sct",
            "552" :"flag-icon-ro",
            "553" :"flag-icon-hu",
            "559" :"flag-icon-sk",
            "564" :"flag-icon-no",
            "5642" :"flag-icon-py",
            "567" :"flag-icon-cy",
            "568" :"flag-icon-es",
            "569" :"flag-icon-es",
            "570" :"flag-icon-es",
            "5707" :"flag-icon-ba",
            "571" :"flag-icon-es",
            "5710" :"flag-icon-rs",
            "6" :"flag-icon-it",
            "7" :"flag-icon-es",
            "7846" :"flag-icon-lt",
            "8220" :"flag-icon-mx",
            "88" :"flag-icon-dk",
            "939" :"flag-icon-pt"}


	    const { eventURL, id } = this.props;

        if (!eventURL.isSport())
            return null
        
        let flag = flags[id]
        if (!flags.hasOwnProperty(id)){
            flag = "flag-icon-un"
        }
	    return (
            <span class={classNames("flag-icon",flag)} />
	    );
  	}
}
